// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartProductQuotationTool.DataAccess;

#nullable disable

namespace SmartProductQuotationTool.Migrations
{
    [DbContext(typeof(SPQTDbContext))]
    [Migration("20230502171246_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartId");

                    b.HasIndex("UserId1");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"), 1L, 1);

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PVCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("CartId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            Description = "",
                            Name = "FX-401R",
                            PVCode = "B",
                            Price = 3600.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 2,
                            Description = "",
                            Name = "FX-401B",
                            PVCode = "B",
                            Price = 3600.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 3,
                            Description = "",
                            Name = "RAX-LCD-LITE",
                            PVCode = "B",
                            Price = 1400.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 4,
                            Description = "",
                            Name = "RAM-1032TZDS",
                            PVCode = "A",
                            Price = 825.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 5,
                            Description = "",
                            Name = "RAM-1032TZDS-CC",
                            PVCode = "B",
                            Price = 1120.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 6,
                            Description = "",
                            Name = "RAX-1048TZDS",
                            PVCode = "A",
                            Price = 555.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 7,
                            Description = "",
                            Name = "RAX-1048TZDS-CC",
                            PVCode = "B",
                            Price = 830.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 8,
                            Description = "",
                            Name = "UIMA4",
                            PVCode = "A",
                            Price = 295.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 9,
                            Description = "",
                            Name = "MGC-CONFIG-KIT4",
                            PVCode = "B",
                            Price = 425.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 10,
                            Description = "",
                            Name = "ALC-480",
                            PVCode = "B",
                            Price = 1160.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 11,
                            Description = "",
                            Name = "PR-300",
                            PVCode = "B",
                            Price = 255.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 12,
                            Description = "",
                            Name = "AGD-048",
                            PVCode = "B",
                            Price = 815.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 13,
                            Description = "",
                            Name = "MGD-32",
                            PVCode = "B",
                            Price = 1105.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 14,
                            Description = "",
                            Name = "PCS-100",
                            PVCode = "B",
                            Price = 210.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 15,
                            Description = "",
                            Name = "MP-3500W",
                            PVCode = "B",
                            Price = 35.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 16,
                            Description = "",
                            Name = "SRM-312R",
                            PVCode = "C",
                            Price = 780.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 17,
                            Description = "",
                            Name = "BB-1001DR",
                            PVCode = "B",
                            Price = 285.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 18,
                            Description = "",
                            Name = "BB-1001D",
                            PVCode = "A",
                            Price = 285.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 19,
                            Description = "",
                            Name = "BB-1001DB",
                            PVCode = "B",
                            Price = 285.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 20,
                            Description = "",
                            Name = "BB-1001DS",
                            PVCode = "C",
                            Price = 490.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 21,
                            Description = "",
                            Name = "BB-1001WPRA",
                            PVCode = "B",
                            Price = 1075.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 22,
                            Description = "",
                            Name = "BB-1001WPA",
                            PVCode = "B",
                            Price = 1075.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 23,
                            Description = "",
                            Name = "BB-1002DR",
                            PVCode = "B",
                            Price = 515.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 24,
                            Description = "",
                            Name = "BB-1002D",
                            PVCode = "B",
                            Price = 515.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 25,
                            Description = "",
                            Name = "BB-1002DB",
                            PVCode = "B",
                            Price = 515.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 26,
                            Description = "",
                            Name = "BB-1002DS",
                            PVCode = "C",
                            Price = 590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 27,
                            Description = "",
                            Name = "BB-1002WPRA",
                            PVCode = "B",
                            Price = 1335.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 28,
                            Description = "",
                            Name = "BB-1002WPA",
                            PVCode = "C",
                            Price = 1335.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 29,
                            Description = "",
                            Name = "BB-1003DR",
                            PVCode = "C",
                            Price = 640.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 30,
                            Description = "",
                            Name = "BB-1003D",
                            PVCode = "B",
                            Price = 640.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 31,
                            Description = "",
                            Name = "BB-1003DB",
                            PVCode = "C",
                            Price = 640.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 32,
                            Description = "",
                            Name = "BB-1003DS",
                            PVCode = "C",
                            Price = 900.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 33,
                            Description = "",
                            Name = "BB-1008DR",
                            PVCode = "C",
                            Price = 1590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 34,
                            Description = "",
                            Name = "BB-1008D",
                            PVCode = "B",
                            Price = 1590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 35,
                            Description = "",
                            Name = "BB-1008DB",
                            PVCode = "C",
                            Price = 1590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 36,
                            Description = "",
                            Name = "BB-1012DR",
                            PVCode = "C",
                            Price = 1770.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 37,
                            Description = "",
                            Name = "BB-1012D",
                            PVCode = "C",
                            Price = 1770.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 38,
                            Description = "",
                            Name = "BB-1012DB",
                            PVCode = "C",
                            Price = 1770.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 39,
                            Description = "",
                            Name = "MIX-4010",
                            PVCode = "A",
                            Price = 130.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 40,
                            Description = "",
                            Name = "MIX-4010-ISO",
                            PVCode = "A",
                            Price = 140.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 41,
                            Description = "",
                            Name = "MIX-4020",
                            PVCode = "A",
                            Price = 160.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 42,
                            Description = "",
                            Name = "MIX-4020-ISO",
                            PVCode = "B",
                            Price = 170.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 43,
                            Description = "",
                            Name = "MIX-4030",
                            PVCode = "A",
                            Price = 110.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 44,
                            Description = "",
                            Name = "MIX-4030-ISO",
                            PVCode = "A",
                            Price = 120.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 45,
                            Description = "",
                            Name = "MIX-4001",
                            PVCode = "A",
                            Price = 28.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 46,
                            Description = "",
                            Name = "MIX-4002",
                            PVCode = "A",
                            Price = 24.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 47,
                            Description = "",
                            Name = "MIX-4003-R",
                            PVCode = "B",
                            Price = 140.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 48,
                            Description = "",
                            Name = "MIX-4003-S",
                            PVCode = "B",
                            Price = 1275.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 49,
                            Description = "",
                            Name = "MIX-4090",
                            PVCode = "A",
                            Price = 600.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 50,
                            Description = "",
                            Name = "MIX-4040",
                            PVCode = "A",
                            Price = 130.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 51,
                            Description = "",
                            Name = "MIX-4041",
                            PVCode = "A",
                            Price = 110.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 52,
                            Description = "",
                            Name = "MIX-4042",
                            PVCode = "B",
                            Price = 195.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 53,
                            Description = "",
                            Name = "MIX-4045",
                            PVCode = "A",
                            Price = 150.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 54,
                            Description = "",
                            Name = "MIX-4046",
                            PVCode = "A",
                            Price = 160.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 55,
                            Description = "",
                            Name = "MIX-4050",
                            PVCode = "A",
                            Price = 170.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 56,
                            Description = "",
                            Name = "MIX-4070",
                            PVCode = "A",
                            Price = 115.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 57,
                            Description = "",
                            Name = "MPS-810MP",
                            PVCode = "N",
                            Price = 190.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 58,
                            Description = "",
                            Name = "MPS-802MP",
                            PVCode = "N",
                            Price = 200.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 59,
                            Description = "",
                            Name = "MPS-822MP",
                            PVCode = "N",
                            Price = 210.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 60,
                            Description = "",
                            Name = "BB-800",
                            PVCode = "N",
                            Price = 45.0,
                            Qty = 1
                        });
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "b307ccdb-b3b1-411c-89b5-c7f17ceeda07",
                            AccessFailedCount = 0,
                            Address1 = "1750 Finch Ave E",
                            Address2 = "",
                            City = "North York",
                            CompanyName = "Seneca College",
                            ConcurrencyStamp = "be50c556-ac5f-48f5-95f1-5e1f540d62b1",
                            Country = "Canada",
                            Discount = 66.0,
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Password = "password1",
                            PhoneNumber = "111-111-1111",
                            PhoneNumberConfirmed = false,
                            PostalCode = "M2J 2X5",
                            Province = "ON",
                            SecurityStamp = "5bf7cee4-8635-486e-bd71-aa125ff2b477",
                            TwoFactorEnabled = false,
                            UserName = "MTL-000001",
                            Website = "https://www.senecacollege.ca/home.html"
                        },
                        new
                        {
                            Id = "9259db75-391d-4249-9776-f4923127d936",
                            AccessFailedCount = 0,
                            Address1 = "108 University Ave",
                            Address2 = "",
                            City = "Waterloo",
                            CompanyName = "Conestoga College",
                            ConcurrencyStamp = "d021ea82-5032-43fb-bd21-f3c6b3abf66f",
                            Country = "Canada",
                            Discount = 68.0,
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Password = "password2",
                            PhoneNumber = "222-222-2222",
                            PhoneNumberConfirmed = false,
                            PostalCode = "N2J 2W2",
                            Province = "ON",
                            SecurityStamp = "845a842f-31f9-4dd3-b346-7a77524b2677",
                            TwoFactorEnabled = false,
                            UserName = "MTL-000002",
                            Website = "https://www.conestogac.on.ca"
                        },
                        new
                        {
                            Id = "bfe76dd5-13bf-4f87-b227-8d856768907c",
                            AccessFailedCount = 0,
                            Address1 = "200 University Ave W",
                            Address2 = "",
                            City = "Waterloo",
                            CompanyName = "University of Waterloo",
                            ConcurrencyStamp = "ea363e0a-f8cd-41f8-b388-bfcc46e63027",
                            Country = "Canada",
                            Discount = 70.0,
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Password = "password3",
                            PhoneNumber = "333-333-3333",
                            PhoneNumberConfirmed = false,
                            PostalCode = "N2L 3G1",
                            Province = "ON",
                            SecurityStamp = "58df2bce-2096-4161-a277-a61096efb661",
                            TwoFactorEnabled = false,
                            UserName = "MTL-000003",
                            Website = "https://uwaterloo.ca"
                        },
                        new
                        {
                            Id = "2d20eca2-5488-4f15-83e8-f0ed67f749db",
                            AccessFailedCount = 0,
                            Address1 = "27 King's College Circle",
                            Address2 = "",
                            City = "Waterloo",
                            CompanyName = "University of Toronto",
                            ConcurrencyStamp = "0dc13c29-21b8-4bac-9afa-48e7aba74e9d",
                            Country = "Canada",
                            Discount = 72.0,
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Password = "password4",
                            PhoneNumber = "444-444-4444",
                            PhoneNumberConfirmed = false,
                            PostalCode = "M5S 1A1",
                            Province = "ON",
                            SecurityStamp = "539510ea-ed67-430b-9107-d78c7ad9b14b",
                            TwoFactorEnabled = false,
                            UserName = "MTL-000004",
                            Website = "https://www.utoronto.ca"
                        });
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Cart", b =>
                {
                    b.HasOne("SmartProductQuotationTool.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Inventory", b =>
                {
                    b.HasOne("SmartProductQuotationTool.Entities.Cart", null)
                        .WithMany("Inventories")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Cart", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
