// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartProductQuotationTool.DataAccess;

#nullable disable

namespace SmartProductQuotationTool.Migrations
{
    [DbContext(typeof(SPQTDbContext))]
    partial class SPQTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PVCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            Description = "Intelligent Fire Alarm Control Unit c/w 1 Intelligent Loop compatible with MGC Devices 4000 Series only)\r\n 	Expandable to three SLCs with the addition of the Dual Loop Controller ALC-480.\r\n 	1  20 Character  by 4 Line  Back-Lit LCD Display\r\n 	4  Class A/B (Style Z/Y) NAC Circuits\r\n 	Four Event Display Queues\r\n 	c/w UB-1024DS Universal Backbox & DOX-1024DSR RED Door\r\n 	Space for 2 RAX-1048TZDS LED Annunciator Modules\r\n* Standard RED Door",
                            Image = "https://mircom.com/wp-content/uploads/products/FX-401-front_sm-1.jpg",
                            Level = 1,
                            Name = "FX-401R",
                            PVCode = "B",
                            Price = 3600.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 2,
                            Description = "Intelligent Fire Alarm Control Unit c/w 1 Intelligent Loop compatible with MGC Devices 4000 Series only)\r\n 	Expandable to three SLCs with the addition of the Dual Loop Controller ALC-480.\r\n 	1  20 Character  by 4 Line  Back-Lit LCD Display\r\n 	4  Class A/B (Style Z/Y) NAC Circuits\r\n 	Four Event Display Queues\r\n 	c/w UB-1024DS Universal Backbox & DOX-1024DSR RED Door\r\n 	Space for 2 RAX-1048TZDS LED Annunciator Modules\r\n* Standard BLACK Door",
                            Image = "https://mircom.com/wp-content/uploads/products/FX-401-front_sm-1.jpg",
                            Level = 1,
                            Name = "FX-401B",
                            PVCode = "B",
                            Price = 3600.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 3,
                            Description = "Remote LCD Annunciator, MIMIC Display for FX-400, FX-401, FX-3318, FX-3500 c/w Large 4 x 20 Character Back-Lit LCD Display, Four Event Display Queues. Common Controls, Mounts in BB-1000 Series Enclosure",
                            Image = "https://mircom.com/wp-content/uploads/products/RAX-LCD-LITE.png",
                            Level = 2,
                            Name = "RAX-LCD-LITE",
                            PVCode = "B",
                            Price = 1400.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 4,
                            Description = "Main Annunciator Chassis  c/w 32 Bi-colored LEDs, 32 Zoned Trouble LEDs\r\nCommon Indicators --\r\nAC On, Common Trouble, Auxiliary Disconnect,\r\n2 Stage Acknowledge & General Alarm Activate (if Config.)\r\nCommon Controls --\r\nReset, Lamp Test,  Fire Drill, Auxiliary Disconnect, \r\nLocal Buzzer & Signal Silence. Mounts in BB-1000 Series Enclosure",
                            Image = "https://mircom.com/wp-content/uploads/products/RAM-1032TZDS_front.png",
                            Level = 2,
                            Name = "RAM-1032TZDS",
                            PVCode = "A",
                            Price = 825.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 5,
                            Description = "Main Annunciator Chassis  c/w 32 Bi-colored LEDs, 32 Zoned Trouble LEDs\r\nCommon Indicators -- AC On, Common Trouble, Auxiliary Disconnect,\r\n2 Stage Acknowledge & General Alarm Activate (if Config.)\r\nCommon Controls -- Reset, Lamp Test,  Fire Drill, Auxiliary Disconnect, \r\nLocal Buzzer & Signal Silence\r\nMounts in BB-1000 Series enclosure or BB-5008 or BB-5014",
                            Image = "https://mircom.com/wp-content/uploads/products/RAM-1032TZDS-CC-1-1024x1018.png",
                            Level = 2,
                            Name = "RAM-1032TZDS-CC",
                            PVCode = "B",
                            Price = 1120.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 6,
                            Description = "Adder Annunciator Chassis c/w 48 Bi-Coloured LEDs; 48 Zoned Trouble LED's\r\nMounts in BB-1000 Series enclosure",
                            Image = "https://mircom.com/wp-content/uploads/products/RAX-1048TZDS.png",
                            Level = 2,
                            Name = "RAX-1048TZDS",
                            PVCode = "A",
                            Price = 555.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 7,
                            Description = "Conformal Coated Adder Annunciator Chassis c/w 48 Bi-Coloured LEDs; 48 Zoned Trouble LED's. Mounts in BB-1000 or BB-5000 Series Enclosure.",
                            Image = "https://mircom.com/wp-content/uploads/products/RAX-1048TZS-CC-1-1024x961.png",
                            Level = 2,
                            Name = "RAX-1048TZDS-CC",
                            PVCode = "B",
                            Price = 830.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 8,
                            Description = "Interface for Configuring FleXNet™, FA-300 Series, FX-2000 Series, FX-401, FX-3500, QX-5000, UDACT-300, and MR-2300 Series",
                            Image = "https://mircom.com/wp-content/uploads/products/UIMA4.png",
                            Level = 3,
                            Name = "UIMA4",
                            PVCode = "A",
                            Price = 295.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 9,
                            Description = "Fire Panel Configuration Kit4 With UIMA4",
                            Image = "",
                            Level = 3,
                            Name = "MGC-CONFIG-KIT4",
                            PVCode = "B",
                            Price = 425.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 10,
                            Description = "FX-401 Dual Loop Controller Module 480 points (MGC Devices 4000 Series Compatible)",
                            Image = "",
                            Level = 4,
                            Name = "ALC-480",
                            PVCode = "B",
                            Price = 1160.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 11,
                            Description = "Polarity Reversal & City Tie c/w Alarm, Supervisory & Trouble Transmit Capabilities",
                            Image = "https://mircom.com/wp-content/uploads/products/PR-300.png",
                            Level = 4,
                            Name = "PR-300",
                            PVCode = "B",
                            Price = 255.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 12,
                            Description = "Adder Graphic Driver Board, c/w 48 Supervised Outputs, Output Connections via Terminals or Ribbon Cable\r\nMounts in Graphic Wall box",
                            Image = "https://mircom.com/wp-content/uploads/products/AGD-048-front.jpg",
                            Level = 4,
                            Name = "AGD-048",
                            PVCode = "B",
                            Price = 815.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 13,
                            Description = "Master Graphic Driver Board c/w, Fire Alarm Common Control Switch Inputs & LED Outputs\r\n32 Supervised Outputs, Output Connections via Terminals or Ribbon Cable\r\nMounts in Graphic Wall box",
                            Image = "https://mircom.com/wp-content/uploads/products/MGD-32-front.jpg",
                            Level = 4,
                            Name = "MGD-32",
                            PVCode = "B",
                            Price = 1105.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 14,
                            Description = "Power Supply Interface Board",
                            Image = "",
                            Level = 4,
                            Name = "PCS-100",
                            PVCode = "B",
                            Price = 210.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 15,
                            Description = "Solenoid End of Line Resistor 47K, White Plate",
                            Image = "",
                            Level = 4,
                            Name = "MP-3500W",
                            PVCode = "B",
                            Price = 35.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 16,
                            Description = "SMART Relay Module with Enclosure (12) RED",
                            Image = "https://mircom.com/wp-content/uploads/products/SRM-312R_right.jpg",
                            Level = 4,
                            Name = "SRM-312R",
                            PVCode = "C",
                            Price = 780.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 17,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators (Houses 1 Module)\r\nRED Door & Black Backbox (12.75\"W X 9\"L X 1.85\"D without door)\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1001DR.png",
                            Level = 5,
                            Name = "BB-1001DR",
                            PVCode = "B",
                            Price = 285.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 18,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators (Houses 1 Module)\r\nWHITE Door & Black Backbox (12.75\"W X 9\"L X 1.85\"D without door)\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1001DR.png",
                            Level = 5,
                            Name = "BB-1001D",
                            PVCode = "A",
                            Price = 285.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 19,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators (Houses 1 Module)\r\nBLACK Door & Black Backbox (12.75\"W X 9\"L X 1.85\"D without door)\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1001DR.png",
                            Level = 5,
                            Name = "BB-1001DB",
                            PVCode = "B",
                            Price = 285.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 20,
                            Description = "NEW Semi-Flush Backbox for Series 1000 Annunciators (Houses 1 Module)\r\nStainless Steel Finish\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1001DR.png",
                            Level = 5,
                            Name = "BB-1001DS",
                            PVCode = "C",
                            Price = 490.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 21,
                            Description = "Weather Protected Backbox for Series 1000 Annunciators (Houses 1 Module)\r\n 	Dimensions: (11-11/32\" Height, 13\" Width, 3.5\" Depth)\r\n 	Rated for Outdoor Environment: +50°C to -40°C - 95% R.H. @60°C\r\n 	Lexan sealed window, to protect against the challenges of an outdoor application\r\n 	Surface mount application. RED Door.\r\n 	NOTE: there is no need for thermostat or heater.  RAM-1032TZDS-CC must be ordered separately to match UL, ULC installation requirements",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1001_WPRA_Remote_Outdoor_Annunciator_Conformal_Coated_UL_ULC_approved_Weather_Protected_Fire_Label-1.png",
                            Level = 5,
                            Name = "BB-1001WPRA",
                            PVCode = "B",
                            Price = 1075.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 22,
                            Description = "Weather Protected Backbox for Series 1000 Annunciators (Houses 1 Module)\r\n 	Dimensions: (11-11/32\" Height, 13\" Width, 3.5\" Depth)\r\n 	Rated for Outdoor Environment: +50°C to -40°C - 95% R.H. @60°C\r\n 	Lexan sealed window, to protect against the challenges of an outdoor application\r\n 	Surface mount application. WHITE Door.\r\n 	NOTE: there is no need for thermostat or heater.  RAM-1032TZDS-CC must be ordered separately to match UL, ULC installation requirements",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1001_WPRA_Remote_Outdoor_Annunciator_Conformal_Coated_UL_ULC_approved_Weather_Protected_Fire_Label-1.png",
                            Level = 5,
                            Name = "BB-1001WPA",
                            PVCode = "B",
                            Price = 1075.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 23,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 2 Modules) \r\nRED Door & Black Backbox (18”H x 12.75”W x 1.85”D)\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1002DS.png",
                            Level = 5,
                            Name = "BB-1002DR",
                            PVCode = "B",
                            Price = 515.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 24,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 2 Modules) \r\nWHITE Door & Black Backbox (18”H x 12.75”W x 1.85”D)\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1002DS.png",
                            Level = 5,
                            Name = "BB-1002D",
                            PVCode = "B",
                            Price = 515.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 25,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 2 Modules) \r\nBLACK Door & Black Backbox (18”H x 12.75”W x 1.85”D)\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1002DS.png",
                            Level = 5,
                            Name = "BB-1002DB",
                            PVCode = "B",
                            Price = 515.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 26,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 2 Modules) \r\nStainless Steel Finish (18”H x 12.75”W x 1.85”D)\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1002DS.png",
                            Level = 5,
                            Name = "BB-1002DS",
                            PVCode = "C",
                            Price = 590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 27,
                            Description = "Weather Protected Backbox for Series 1000 Annunciators (Houses 2 Module)\r\n 	Dimensions: (11-11/32\" Height, 13\" Width, 3.5\" Depth)\r\n 	Rated for Outdoor Environment: +50°C to -40°C - 95% R.H. @60°C\r\n 	Lexan sealed window, to protect against the challenges of an outdoor application\r\n 	Surface mount application. RED Door.\r\n 	NOTE: there is no need for thermostat or heater. RAM-1032TZDS-CC and RAX-1048TZDS-CC must be ordered separately to match UL, ULC installation requirements.",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1002WPRA_Remote_Outdoor_Annunciator_Conformal_Coated_UL_ULC_label-1-1000x1000.png",
                            Level = 5,
                            Name = "BB-1002WPRA",
                            PVCode = "B",
                            Price = 1335.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 28,
                            Description = "Weather Protected Backbox for Series 1000 Annunciators (Houses 2 Module)\r\n 	Dimensions: (11-11/32\" Height, 13\" Width, 3.5\" Depth)\r\n 	Rated for Outdoor Environment: +50°C to -40°C - 95% R.H. @60°C\r\n 	Lexan sealed window, to protect against the challenges of an outdoor application\r\n 	Surface mount application. WHITE Door.\r\n 	NOTE: there is no need for thermostat or heater. RAM-1032TZDS-CC and RAX-1048TZDS-CC must be ordered separately to match UL, ULC installation requirements.",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1002WPRA_Remote_Outdoor_Annunciator_Conformal_Coated_UL_ULC_label-1-1000x1000.png",
                            Level = 5,
                            Name = "BB-1002WPA",
                            PVCode = "C",
                            Price = 1335.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 29,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 3 Modules)\r\nRED Door & Black Backbox (12.75\"W X 26.4\"L X 1.85\"D) without door\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1003D.png",
                            Level = 5,
                            Name = "BB-1003DR",
                            PVCode = "C",
                            Price = 640.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 30,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 3 Modules)\r\nWHITE Door & Black Backbox (12.75\"W X 26.4\"L X 1.85\"D) without door\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1003D.png",
                            Level = 5,
                            Name = "BB-1003D",
                            PVCode = "B",
                            Price = 640.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 31,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 3 Modules)\r\nBLACK Door & Black Backbox (12.75\"W X 26.4\"L X 1.85\"D) without door\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1003D.png",
                            Level = 5,
                            Name = "BB-1003DB",
                            PVCode = "C",
                            Price = 640.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 32,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 3 Modules)\r\nStainless Steel Finish (12.75\"W X 26.4\"L X 1.85\"D) without door\r\nMounts over standard electrical box by others",
                            Image = "https://mircom.com/wp-content/uploads/products/BB-1003D.png",
                            Level = 5,
                            Name = "BB-1003DS",
                            PVCode = "C",
                            Price = 900.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 33,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 8 Modules)\r\nRED  Door & Black Backbox (33”H x 22.5”W x 1.85”D)\r\nMounts over standard electrical box by others",
                            Image = "",
                            Level = 5,
                            Name = "BB-1008DR",
                            PVCode = "C",
                            Price = 1590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 34,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 8 Modules)\r\nWHITE  Door & Black Backbox (33”H x 22.5”W x 1.85”D)\r\nMounts over standard electrical box by others",
                            Image = "",
                            Level = 5,
                            Name = "BB-1008D",
                            PVCode = "B",
                            Price = 1590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 35,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 8 Modules)\r\nBLACK Door & Black Backbox (33”H x 22.5”W x 1.85”D)\r\nMounts over standard electrical box by others",
                            Image = "",
                            Level = 5,
                            Name = "BB-1008DB",
                            PVCode = "C",
                            Price = 1590.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 36,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 12 Modules)\r\nRED Door & Black Backbox (45”H x 22.5”W x 1.85”D)\r\nMounts Over Standard Electrical Box by Others",
                            Image = "https://mircom.com/wp-content/uploads/2016/10/products-bb-1012-remote-enclosure.jpg",
                            Level = 5,
                            Name = "BB-1012DR",
                            PVCode = "C",
                            Price = 1770.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 37,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 12 Modules)\r\nWHITE Door & Black Backbox (45”H x 22.5”W x 1.85”D)\r\nMounts Over Standard Electrical Box by Others",
                            Image = "https://mircom.com/wp-content/uploads/2016/10/products-bb-1012-remote-enclosure.jpg",
                            Level = 5,
                            Name = "BB-1012D",
                            PVCode = "C",
                            Price = 1770.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 38,
                            Description = "Semi-Flush Backbox for Series 1000 Annunciators  (Houses 12 Modules)\r\nBLACK Door & Black Backbox (45”H x 22.5”W x 1.85”D)\r\nMounts Over Standard Electrical Box by Others",
                            Image = "https://mircom.com/wp-content/uploads/2016/10/products-bb-1012-remote-enclosure.jpg",
                            Level = 5,
                            Name = "BB-1012DB",
                            PVCode = "C",
                            Price = 1770.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 39,
                            Description = "4000 Series Photoelectric Detector W/O Isolation",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4010-MIX-4020-tilt_lg.jpg",
                            Level = 6,
                            Name = "MIX-4010",
                            PVCode = "A",
                            Price = 130.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 40,
                            Description = "4000 Series Photoelectric Detector with Isolation",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4010-MIX-4020-tilt_lg.jpg",
                            Level = 6,
                            Name = "MIX-4010-ISO",
                            PVCode = "A",
                            Price = 140.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 41,
                            Description = "4000 Series Multi Sensor - Photoelectric heat W/O Isolation",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4010-MIX-4020-tilt_lg.jpg",
                            Level = 6,
                            Name = "MIX-4020",
                            PVCode = "A",
                            Price = 160.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 42,
                            Description = "4000 Series Multi Sensor - Photoelectric heat with Isolation",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4010-MIX-4020-tilt_lg.jpg",
                            Level = 6,
                            Name = "MIX-4020-ISO",
                            PVCode = "B",
                            Price = 170.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 43,
                            Description = "4000 Series Tri-Mode Heat Detector W/O Isolation",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4030-tilt_lg.jpg",
                            Level = 6,
                            Name = "MIX-4030",
                            PVCode = "A",
                            Price = 110.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 44,
                            Description = "4000 Series Tri-Mode Heat Detector with Isolation",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4030-tilt_lg.jpg",
                            Level = 6,
                            Name = "MIX-4030-ISO",
                            PVCode = "A",
                            Price = 120.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 45,
                            Description = "4000 Series 6\" Detector Base",
                            Image = "https://mircom.com/wp-content/uploads/products/bases-2-1.jpg",
                            Level = 6,
                            Name = "MIX-4001",
                            PVCode = "A",
                            Price = 28.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 46,
                            Description = "4000 Series 4\" Detector Base",
                            Image = "https://mircom.com/wp-content/uploads/products/bases-2-1.jpg",
                            Level = 6,
                            Name = "MIX-4002",
                            PVCode = "A",
                            Price = 24.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 47,
                            Description = "4000 Series Relay Base",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4003-S-R-with-MIX-4020-ISO-1-scaled.jpg",
                            Level = 6,
                            Name = "MIX-4003-R",
                            PVCode = "B",
                            Price = 140.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 48,
                            Description = "4000 Series Sounder Base",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4003-S-R-with-MIX-4010-ISO-1.jpg",
                            Level = 6,
                            Name = "MIX-4003-S",
                            PVCode = "B",
                            Price = 1275.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 49,
                            Description = "4000 Series Addressable Device Programmer",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4090.png",
                            Level = 6,
                            Name = "MIX-4090",
                            PVCode = "A",
                            Price = 600.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 50,
                            Description = "4000 Series Dual Input Module",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4040.jpg",
                            Level = 6,
                            Name = "MIX-4040",
                            PVCode = "A",
                            Price = 130.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 51,
                            Description = "4000 Series Mini Dual Input Module",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4041-e1604012409118.jpg",
                            Level = 6,
                            Name = "MIX-4041",
                            PVCode = "A",
                            Price = 110.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 52,
                            Description = "4000 Series Conventional Zone Module",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4042.jpg",
                            Level = 6,
                            Name = "MIX-4042",
                            PVCode = "B",
                            Price = 195.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 53,
                            Description = "4000 Series Dual Relay Module",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4045.jpg",
                            Level = 6,
                            Name = "MIX-4045",
                            PVCode = "A",
                            Price = 150.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 54,
                            Description = "4000 Series Supervised Output Module",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4046.jpg",
                            Level = 6,
                            Name = "MIX-4046",
                            PVCode = "A",
                            Price = 160.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 55,
                            Description = "Sync Module",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4050.png",
                            Level = 6,
                            Name = "MIX-4050",
                            PVCode = "A",
                            Price = 170.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 56,
                            Description = "4000 Series Isolator Module",
                            Image = "https://mircom.com/wp-content/uploads/products/MIX-4070.jpg",
                            Level = 6,
                            Name = "MIX-4070",
                            PVCode = "A",
                            Price = 115.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 57,
                            Description = "MP 1 STAGE ADDR DOUBLE ACTION PULL STATION ULC",
                            Image = "https://mircom.com/wp-content/uploads/products/MPS-810.png",
                            Level = 7,
                            Name = "MPS-810MP",
                            PVCode = "N",
                            Price = 190.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 58,
                            Description = "MP 2 STAGE ADDRESSABLE PULL STATION ULC",
                            Image = "",
                            Level = 7,
                            Name = "MPS-802MP",
                            PVCode = "N",
                            Price = 200.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 59,
                            Description = "MP MAGLOCK 2 STAGE ADDR DOUBLE ACTION PULL STATION ULC",
                            Image = "",
                            Level = 7,
                            Name = "MPS-822MP",
                            PVCode = "N",
                            Price = 210.0,
                            Qty = 1
                        },
                        new
                        {
                            InventoryId = 60,
                            Description = "Surface Backbox For 800 Series Manual Station",
                            Image = "",
                            Level = 7,
                            Name = "BB-800",
                            PVCode = "N",
                            Price = 45.0,
                            Qty = 1
                        });
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartProductQuotationTool.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartProductQuotationTool.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartProductQuotationTool.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartProductQuotationTool.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartProductQuotationTool.Entities.Cart", b =>
                {
                    b.HasOne("SmartProductQuotationTool.Entities.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartProductQuotationTool.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
